### PR TITLE
Various improvements on handling side cases

### PR DESCRIPTION
**Pull request by CyanDevs**
- Better handle timing out while in queue
  - Prevent lost queue items due to Jenkins garbage collection
  - Handle failed triggers such as disabled jobs
  - Prevent waiting for cancelled queue items to start

Signed-off-by: Chris Yan <chrisyan@microsoft.com>

### CODE REVIEW

**Comment by CyanDevs** [comment]
> @CyanDevs Do you want the jenkins operator image to be a part of your docker image work or should I own it?

Apologies in advance if I'm misunderstanding you. This question seems a little off topic for the pull request at hand, so instead let's discuss that as part of the docker image work.

**Comment by BRMcLaren** [comment]
@CyanDevs to test this script works we would need to upload it to the docker repository. It is not off topic as there is no evidence within this pull request that the changes do work.

**Comment by BRMcLaren** [comment]
@CyanDevs I believe there is some context being missed here. The only way we currently have to test the script is to manually build the image that uses this script and upload it. It's why the ownership question comes up. Because I can go ahead, build it and upload it and pray or you can. Alternatively we should add a unit test in.

I suppose that since this isn't live we can go with the push and pray approach though.. but today would be the last day for that. Is there any additional changes you can think of within or outside of this PR?

**Comment by CyanDevs** [comment]
Thank you for the clarification. I would be happy to share the responsibility in generating the Docker image if you could show me how.

As for evidence, we don't have any tests set up yet so there is not immediately available evidence of function. Instead, I've been running my changes manually by triggering a job on Jenkins using the API credentials for the job here: https://openenclave-jenkins.eastus.cloudapp.azure.com/job/openenclave-mbedtls/job/Rhel8BuildClang-8/

Here is a quick build log using this exact PR's script for openenclave-mbedtls/ping which relates to https://openenclave-jenkins.eastus.cloudapp.azure.com/job/openenclave-mbedtls/job/ping/106/
```
Fetching: https://openenclave-jenkins.eastus.cloudapp.azure.com/crumbIssuer/api/json
Triggering a build via POST @ https://openenclave-jenkins.eastus.cloudapp.azure.com/job/openenclave-mbedtls/job/ping/buildWithParameters
Build is queued @ https://openenclave-jenkins.eastus.cloudapp.azure.com/queue/item/6910/api/json
Checking job status at https://openenclave-jenkins.eastus.cloudapp.azure.com/queue/item/6910/api/json (#1/17)
Sleeping for 0.55s...
Checking job status at https://openenclave-jenkins.eastus.cloudapp.azure.com/queue/item/6910/api/json (#2/17)
Job is executing: https://openenclave-jenkins.eastus.cloudapp.azure.com/job/openenclave-mbedtls/job/ping/106/
Getting Console output: https://openenclave-jenkins.eastus.cloudapp.azure.com/job/openenclave-mbedtls/job/ping/106/logText/progressiveText
Started by user jenkinsadmin
Running as SYSTEM
Building remotely on overwatcha1d4f1 (OverWatch) in workspace /home/oeadmin/workspace/openenclave-mbedtls/ping

[ping] $ /bin/sh -xe /tmp/jenkins7147230456266459142.sh
+ echo pong
pong
Finished: SUCCESS

Stream closed with a successful job
```

**Pull request merged**
