### PR TITLE
change 2016 version to 2021.01.28

### PR DESCRIPTION
**Pull request by BRMcLaren**
Signed-off-by: brmclare <brmclare@microsoft.com>

### CODE REVIEW

**Comment by BRMcLaren** [comment]
The image version did not exist from the prior version, so switch to latest stable.

**Comment by BRMcLaren** [comment]
/assign @rs-- 

:) Made a minor mistake in the upgrade image process, one can double-check this is the correct change by checking the image galleries.

**Review by CyanDevs — APPROVED** [review]

**Review by rs-- — APPROVED** [review]

**Comment by BRMcLaren** [comment]
@rs-- @CyanDevs One needs to type /lgtm for the second approval. The PR is automatically approved as I am a root owner, just needs the additional "approval"

**Comment by BRMcLaren** [comment]
LGTM myself because 2 approvals :D

**Pull request merged**
